In [1]:
import numpy as np

In [9]:
arr=np.arange(5,50,5)

In [6]:
arr

array([ 5, 10, 15, 20, 25, 30, 35, 40])

In [18]:
arr = arr.reshape(3,3)
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr[1:,:2]

array([[20, 25],
       [35, 40]])

In [20]:
mat = np.arange(1,26).reshape(5,5)

In [21]:
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])